name: Linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Check formatting
        run: uv run --locked --group lint black --check --diff popsregression examples

      - name: Run linter
        run: uv run --locked --group lint ruff check --output-format=full popsregression examples
